spring:
  config:
    activate:
      on-profile: common
  jpa:
    open-in-view: false
jwt:
  secretKey: ENC(uvRR3r/GGDxBWH5fuINwi8uQVmhDV9lkuDtiDmEJeKnEMNYLlIZ/lfPYSrpn/LLPUtJflpTdSDxXGd6qRIfWrWmvtdS88f8JI3B1yQQ0VQRsywHyg/wB7w==)
  access:
    expiration: 604800000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization
  refresh:
    expiration: 604800000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
